---
- name: Configure OPS445 Linux VM
  hosts: vmlab
  become: yes
  vars:
    seneca_id: swiafe
  tasks:
    - name: Update Apache HTTP Server
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Remove tree package
      yum:
        name: tree
        state: absent

    - name: Set hostname
      hostname:
        name: "{{ seneca_id }}"

    - name: Create a new user with sudo access
      user:
        name: "{{ seneca_id }}"
        state: present
        groups: wheel
        append: yes

    - name: Allow sudo without password for the new user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ seneca_id }}"
        line: "{{ seneca_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Create .ssh directory for the new user
      file:
        path: "/home/{{ seneca_id }}/.ssh"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0700'

    - name: Copy SSH public key for the new user
      ansible.builtin.copy:
        src: /home/swiafe/.ssh/id_rsa.pub
        dest: "/home/{{ seneca_id }}/.ssh/authorized_keys"
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0600'

    - name: Create directory structure for labs
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
